"""empty message

Revision ID: b8ced90b4487
Revises: ab120c5bd8ce
Create Date: 2025-12-06 22:32:12.407582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ced90b4487'
down_revision = 'ab120c5bd8ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('blueprint', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom',
    sa.Column('product', sa.Integer(), nullable=False),
    sa.Column('material', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material'], ['material.id'], ),
    sa.ForeignKeyConstraint(['product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product', 'material')
    )
    op.create_table('bop',
    sa.Column('product', sa.Integer(), nullable=False),
    sa.Column('process', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process'], ['process.id'], ),
    sa.ForeignKeyConstraint(['product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product', 'process')
    )
    op.create_table('use',
    sa.Column('process', sa.Integer(), nullable=False),
    sa.Column('tool', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process'], ['process.id'], ),
    sa.ForeignKeyConstraint(['tool'], ['tool.id'], ),
    sa.PrimaryKeyConstraint('process', 'tool')
    )
    op.create_table('work_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client', sa.Integer(), nullable=False),
    sa.Column('product', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['client'], ['client.id'], ),
    sa.ForeignKeyConstraint(['product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_order')
    op.drop_table('use')
    op.drop_table('bop')
    op.drop_table('bom')
    op.drop_table('tool')
    op.drop_table('product')
    op.drop_table('process')
    op.drop_table('material')
    op.drop_table('client')
    # ### end Alembic commands ###
