"""empty message

Revision ID: d5ff100ad99e
Revises: 27f2873a8ac0
Create Date: 2025-11-26 22:23:31.125774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ff100ad99e'
down_revision = '27f2873a8ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blueprint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.Integer(), nullable=False),
    sa.Column('document_uri', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('use',
    sa.Column('process', sa.Integer(), nullable=False),
    sa.Column('tool', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process'], ['process.id'], ),
    sa.ForeignKeyConstraint(['tool'], ['tool.id'], ),
    sa.PrimaryKeyConstraint('process', 'tool')
    )
    op.create_table('work_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['client'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execute',
    sa.Column('bop', sa.Integer(), nullable=False),
    sa.Column('process', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bop'], ['bop.id'], ),
    sa.ForeignKeyConstraint(['process'], ['process.id'], ),
    sa.PrimaryKeyConstraint('bop', 'process')
    )
    op.create_table('manufacturing',
    sa.Column('word_order', sa.Integer(), nullable=False),
    sa.Column('product', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product'], ['product.id'], ),
    sa.ForeignKeyConstraint(['word_order'], ['work_order.id'], ),
    sa.PrimaryKeyConstraint('word_order', 'product')
    )
    op.create_table('source',
    sa.Column('bom', sa.Integer(), nullable=False),
    sa.Column('material', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bom'], ['bom.id'], ),
    sa.ForeignKeyConstraint(['material'], ['material.id'], ),
    sa.PrimaryKeyConstraint('bom', 'material')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=1)

    op.drop_table('source')
    op.drop_table('manufacturing')
    op.drop_table('execute')
    op.drop_table('work_order')
    op.drop_table('use')
    op.drop_table('bop')
    op.drop_table('bom')
    op.drop_table('blueprint')
    op.drop_table('tool')
    op.drop_table('process')
    op.drop_table('material')
    op.drop_table('client')
    # ### end Alembic commands ###
